server:
  port: 0
endpoints:
  shutdown:
    enabled: true
spring:
  hadoop:
    fsUri: hdfs://localhost:8020
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
